spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/wswork?useTimezone=true&serverTimezone=UTC&useLegacyDate
        username: postgres
        password: root

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: create
        defer-datasource-initialization: true
        properties:
            hibernate:
                format_sql: true
    sql:
        init:
            mode: always
